/*************** Expressionismo Abstrato - Base de Dados ****************/
var exprAbstr = {
	introd:{
		titulo:"O Expressionismo Abstrato",
		subtitulo:"Principais Intérpretes",
		texto:[
			"O Expressionismo Abstrato foi um movimento artístico com origem nos Estados Unidos, cujo auge foi atingido nas décadas posteriores à Segunda Guerra Mundial. Foi o primeiro movimento especificamente americano a atingir influência mundial, colocando Nova Iorque no centro do mundo artístico (posição previamente exercida por Paris, na França). Por vezes, o Expressionismo Abstrato é designado por <i>Escola de Nova Iorque</i>.",
			"O movimento ganhou este nome por combinar a intensidade emocional do expressionismo alemão com a estética antifigurativa das Escolas abstratas da Europa, como o Futurismo, o Bauhaus e o Cubismo Sintético. O termo <i>Expressionismo Abstrato</i> foi usado pela primeira vez em 1952 pelo crítico e colecionador Harold Rosenberg para designar este movimento americano.",
			"São vários os pintores referidos como cultores do Expressionismo Abstrato. Porém, destacam-se Arshile Gorky, Jackson Pollock, Philip Guston, Willem de Kooning, Mark Rothko, Adolph Gottliebe, Franz Kline, Robert Motherwell e Clyfford Still.",
			"A geração de Kooning e Pollock parecia ter sido, entre os expressionistas abstratos, composta por figuras em torno das quais a maioria dos críticos e dos artistas mais jovens se orientava. Incorporaram o emprego de uma paleta agressiva, conjugando os traços geométricos e aleatórios da <i>pintura automática</i>, um empaste pesado e grosseiro de pigmentos sobrepostos. O modo de pintar americano rompeu com a pintura de cavalete e elegeu como suporte a parede ou o chão, o que permitia que o artista tivesse uma nova capacidade para trabalhar dos quatro lados, passando a estar literalmente <i>na</i>, ou <i>dentro da</i> pintura. Utilizavam novos pigmentos, como o pesado empaste feito de areia, vidro moído, cinza vulcânica e a técnica do <i>dripping</i>.",
			"O Expressionismo Abstrato reúne um grande conjunto de manifestações, sendo possível identificar duas tendências principais. Uma, que se integra na corrente da <i>Action Painting</i>, inclui as obras de pintores como Jackson Pollock, Willem deKooning ou Franz Kline. Nas suas obras, bastante gestualistas, a tinta era lançada diretamente na tela, através de gestos instintivos, onde o acaso e o aleatório determinavam a evolução da pintura. A outra tendência, a <i>Color Field</i>, mais meditativa ou <i>mística</i>, integra os pintores Rothko e Gottlieb. Estes artistas exploraram preferencialmente as qualidades tácteis e os efeitos sensitivos da cor e produziram quadros abstratos utilizando poucos elementos, representados com limites indefinidos e relações cromáticas de grande subtileza."
		]
	},
	pintores:[
		{//1-Arshile Gorky
			nome:"Arshile Gorky", nacion:"arménia e americana",
			dataNasc:"19040415", localNasc:"Van Vilayet, Arménia",
			dataMorte:"19480721", localMorte:"Sherman, Connecticut, EUA",
			foto:"ArshileGorky.jpg",
			texto:[
				"Arshile Gorky (1904-1948), foi um pintor surrealista arménio pioneiro e a mais importante influência sobre os membros do movimento expressionista abstrato. O pintor passou a maior parte da sua vida como cidadão dos Estados Unidos. Junto com Mark Rothko, Jackson Pollock e Willem de Kooning, Gorky é considerado um dos mais importantes pintores norte-americanos do século XX. Como tal, especula-se que as suas obras são influenciadas pelo sofrimento e pela perda que o artista sofreu por causa do genocídio arménio.",
				"Gorky nasceu em 15 de abril de 1904, na aldeia de Khorgon, em Van Vilayet, no leste da Arménia. Aos cinco anos, começou a desenhar e a pintar. Por volta da mesma época, o seu pai emigrou para os Estados Unidos para evitar ser mobilizado para exército, deixando para trás a família na cidade de Van. Em 1915, Gorky fugiu de Van durante o genocídio armênio e escapou com sua mãe e suas três irmãs para um território controlado pela Rússia. Após o genocídio, a mãe de Gorky morreu de fome em Erevão em 1919. Quando chegou aos Estados Unidos, em 1920, Gorky, com 16 anos, juntou-se ao seu pai, mas nunca se deram bem.",
				"Gorky estudou na Technical High School de Providence até à primavera de 1921. Depois frequentou a New School of Design, em Boston, no ano de 1924, data da primeira sua pintura conhecida, <i>Park Street Church</i> (), assinada com o pseudónimo <i>Arshile Gorky</i>. O seu nome original era Vostanik Manoug Adoian. Porém como era hábito dos imigrantes na América, mudou o nome para Arshak Gorky. Arshak é um nome real da dinastia arsácida e Gorky significa <i>amargo</i> em russo. Mais tarde, adotou o nome Arshile, a versão caucásica do nome real Arshak. No processo de reinventar a sua identidade, Gorky teria afirmado ser um nobre da Geórgia e até mesmo dito às pessoas que era parente do grande escritor russo Maxim Gorky.",
				"Em 1925, Gorky mudou-se para Nova York, adquirindo o seu primeiro ateliê. Cinco anos depois participou na sua primeira exposição coletiva, <i>Exhibition of Work of 46 Painters and Sculptors under 35 Years of Age</i>, no Museu de Arte Moderna de Nova York. O artista teve sua primeira exposição individual em 1934, nas Mellon Galleries, em Filadélfia. Demorou vinte anos, pintando no estilo de Cézanne e depois no de Picasso, até chegar a seu estilo maduro evidente em <i>The Liver is the Cock's Comb</i> (O Fígado é a Crista do Galo, 1944). Na obra, tudo está em vias de se transformar em outra coisa. As forças biomórficas tem Miró como referência, enquanto a cor brilhante e o seu tratamento espontâneo refletem o entusiasmo do artista por Kandinsky. A força de atração e repulsão das formas e o seu interrelacionamento dinâmico, no entanto, são características exclusivamente suas.",
				"Gorky foi o personagem principal da transição entre o surrealismo norte-americano e o movimento que se seguiu nos Estados Unidos, o Expressionismo Abstrato. A sua obra inicial foi realizada em condições de extrema pobreza ainda na Arménia, mas já evidenciava uma progressão constante através dos estilos modernistas básicos. Durante a Primeira Guerra, começou a fazer explorações cada vez mais corajosas e, nos anos 1930, já buscava o surrealismo.",
				"Após dois anos de grande felicidade, 1943-1945, com o auge da produção artística, um novo casamento e o nascimento de dois filhos, a desgraça cai sobre Gorky. A crítica à sua exposição de 1945 foi dececionante: alguns acusaram-no de ser um mero seguidor da arte europeia. Em janeiro de 1946, o seu ateliê incendeia-se e Gorky perde os trabalhos em curso. Um mês mais tarde, fica a saber que sofre de um cancro do cólon. Os tratamentos deixam-no muito debilitado. A 26 de junho de 1948, fica gravemente ferido num acidente de viação que lhe paralisa o braço com que pinta. Alguns dias depois, a sua mulher, que tem um caso com o seu amigo Matta, abandona-o. Despedaçado física e moralmente, Arshile Gorky enforca-se no dia 21 de julho. O Whitney Museum organizará uma retrospetiva do artista em 1951.",
				"Harold Rosenberg, um dos principais críticos do Expressionismo Abstrato, diz que a obra de Gorky nessa época era <i>cheia de metáforas e associações,  entre organismos estranhos e macios e fendas e borrões insidiosos, pétalas que lembram garras numa selva de partes corporais flácidas, fístulas intestinais, genitálias e várias dobras nos membros</i>."
			],
			obras:[
				{
					titl:"Park Street Church", ano:1924, imag:"ago01.jpg",
					texto:"Primeira obra conhecida de Gorky, então com 19 anos de idade, seguindo uma corrente impressionista."
				},
				{
					titl:"The Artist with his Mother", ano:1936, imag:"ago02.jpg",
					texto:"Gorky viveu permanentemente inquietado pela dolorosa saudade da mãe, morta de fome em 1919. Nesta pintura recria a sua recordação, a partir de uma fotografia, tirada em 1912, do artista, então com 8 anos, com a sua mãe. Vestida com roupas simples de campo, a sua mãe é uma figura distante e magra, com olhos notáveis e penetrantes. Gorky retratou-a com uma simplicidade clássica e cuidadosa, transformando a sua beleza sombria nas características perfeitas de um ícone da igreja do Leste Europeu."
				},
				{
					titl:"Garden in Sochi", ano:1943, imag:"ago03.jpg",
					texto:"Esta pintura (a primeira de seis sobre este tema) representa a reflexão nostálgica de Gorky sobre o jardim que fazia parte da fazenda do seu pai perto do Lago Van da sua Arménia natal. É notória a influência de Miró, em termos de paleta, composição e formas. Num texto datilografado entregue ao Museu de Arte Moderna, Gorky descreveu o jardim e os seus objetos (incluindo cenouras e porcos-espinhos), bem como os seus motivos retratados, incluindo mulheres esfregando seus seios em rochas para ver seus desejos cumpridos, e a <i>Árvore Sagrada</i> com pedaços rasgados de roupas de pessoas que visitam a árvore. Na pintura é identificável a imagem central de um sapato elegante que o pai de Gorky supostamente lhe deu antes de deixar a Arménia. No entanto, o espectador que insiste em uma leitura muito específica das imagens de Gorky não será totalmente recompensado, pois o prazer maior é permitir que os seus títulos sugiram um assunto, e então permitir que as nossas próprias memórias e associações se misturem com o que está no tela de pintura. Nesse sentido, as suas obras permitem que o espectador se divirta no jogo lírico da cor, seguindo o ritmo das formas curvas enquanto elas nos ajudam a abrir as memórias de nossas próprias experiências que percebemos serem comuns a toda a humanidade."
				},
				{
					titl:"Waterfall", ano:1943, imag:"ago04.jpg",
					texto:"Esta pintura pertenca à fase em que Gorky se dedicou a produzir uma série de pinturas que se referem a formas naturais e rústicas. Este tema era perfeito para ele: a ideia de uma arte de sugestão e ocultação, de formas dissolvidas ou sobrepostas de perplexidades. Nesta pintura, formas amorfas e pingos de tinta líquida sugerem a fluidez de uma cascata. Mas, mesmo aqui, houve deliberação: uma flecha ostentada por uma figura reta (influência de Miró) aponta para baixo numa série de fluxos e obstruções, em que a paisagem se torna áspera e desmorona numa profusão gloriosamente desleixada. Ele escreveu: <i>Oposta a essa visão de destruição está a visão da criação, nas aparências que se dissolvem e se reformam</i>."
				},
				{
					titl:"The Liver is the Cock's Comb", ano:1944, imag:"ago05.jpg",
					texto:"O título altamente descritivo desta pintura representa definitivamente os sentimentos que Gorky está tentando transmitir. Mas também é mais sábio e menos sugestivo do que se imagina. À primeira vista, parece um vibrante, mas confuso, desenho animado da Disney. Mas, observando melhor, não vemos personagens divertidas na pintura. Existem curiosas formas fálico-sexuais, formas afiadas e algo que se parece com um ovo cozido. Esta pintura foi inspirada por uma fazenda na Virgínia, pertencente ao seu segundo casal de sogros. Gorky sempre sentiu uma proximidade com a natureza como uma fuga à dor do genocídio arménio e à morte da sua mãe. A pintura parece amarrar tudo num pequeno arco. Ele representa a sua terra natal (agora Turquia), a sua imigração para os EUA, a sua frustração sexual ao longo da sua vida e a paz que encontrou na natureza."
				},
				{
					titl:"One Year the Milkweed", ano:1944, imag:"ago06.jpg",
					texto:"Camadas semitransparentes de tinta foram lavados de forma desigual na tela, e formas evocativas, mas indistintas, foram escovadas. Os tons verdes e castanhos sugerem uma paisagem, mas não há formas de paisagem identificáveis nem qualquer recessão espacial. Em vez disso, os gotejamentos verticais e a alternância de tons claros e profundos criam um efeito brilhante em toda a superfície da imagem. Inspirada por uma fazenda dos seus sogros, na Virgínia, a pintura poderia ser descrita como uma espécie de pastoral abstrata. A técnica solta de lavagem reflete o interesse de Gorky pelo procedimento surrealista do automatismo, que explorava efeitos aparentemente acidentais obtidos pela pintura e pelo desenho sem premeditação. Na teoria surrealista, esses efeitos acidentais eram vistos como reveladores dos processos inconscientes de pensamento. O título foi dado à pintura pelo amigo de Gorky, o grande poeta e teórico surrealista André Breton."
				}
			]
		},
		{//2-Jackson Pollock
			nome:"Jackson Pollock", nacion:"americana",
			dataNasc:"19120128", localNasc:"Cody, Wyoming, EUA",
			dataMorte:"19560811", localMorte:"Springs, New York. EUA",
			foto:"JacksonPollock.jpg",
			texto:[
				"Jackson Pollock nasceu em Cody, no estado de Wyoming, EUA, em 1912. Era o mais novo de cinco irmãos e vinha de uma família sem grande segurança económica e social. Foi abandonado pelo pai aos 9 anos de idade, e mal tinha auxílio da mãe. Habituou-se a viver dentro de uma instabilidade emocional, mergulhado em sentimentos de medo, baixa auto-estima e insegurança, que se agravaram com a sua adolescência. Tinha um carácter indisciplinado e imprudente. Com o avançar dos anos, o problema do álcool, muito presente na sua vida, intensificou todas estas características da sua personalidade. No entanto, e apesar de todas as dificuldades pelas quais passava, sempre manteve o sonho de um dia vir a ser pintor.",
				"Em 1930, muda-se para Nova Iorque, e frequentou as aulas do pintor Thomas Hart Benton. Com ele, tomou conhecimento de alguns conceitos de composição e espaço. Conforme foi desenvolvendo os seus gostos artísticos, ganhou grande interesse por pintores muralistas mexicanos, como Diego Rivera, mas principalmente por David Siqueiros. Interessou-se, sobretudo, pelas técnicas utilizadas nas suas pinturas, tais como: <i>airbrushing</i>, <i>pouring</i> e <i>dripping</i>. Mais tarde, Pollock recebe algumas influências de pintores cubistas, como Pablo Picasso, e pós-cubistas como Joan Miró.",
				"Tudo mudou na vida de Pollock quando conheceu a sua mulher, a pintora Lee Krasner, e também quando a galerista Peggy Guggenhaim surgiu na sua vida. Peggy convidou-o para expor na sua galeria, e foi assim que começou a estar rodeado de pessoais mais influentes, artistas e pessoas dentro da elite artística, como o pintor Willem de Kooning, um cultor do movimento expressionista abstracto. O surrealismo também foi algo que lhe causou bastante influência em termos conceptuais.",
				"Na altura, o trabalho de Pollock estava exposto em galerias de arte em Nova Iorque, mas, mesmo assim, não atingiu o seu auge. O pico deu-se, em 1949, com as fotografias a preto-e-branco captadas por Hans Namuth, um fotógrafo alemão. ",
				"Jackson Pollock via a arte como um processo de auto-descoberta, de denúncia de medos intrínsecos e de fuga de sentimentos reprimidos. O pintor não pretendia representar, através da pintura, a época em que vivia. Pretendia, sim, ir além da representação de regimes totalitários frequentes na época, além da bomba atómica e da guerra civil. Afinal, cada época histórica tem tendência para encontrar a sua própria técnica. Diz-se que o Expressionismo Abstracto teve origem em dois acontecimentos marcantes, entre eles, a grande depressão financeira nos EUA, em 1929, e a Segunda Guerra Mundial.",
				"Pollock é uma figura central deste movimento, conhecido pela utilização da técnica <i>drip + painting = dripping</i>. <i>Dripping</i> é a técnica em que a tinta é lançada directamente sobre a superfície da tela. Ao contrário do que se pensa, o pintor era bastante perfeccionista, cada detalhe nos seus quadros era planeado. Cada traço, cada enquadramento, cada efeito cromático, tudo arquitectado ao pormenor. O pintor dava bastante importância à precisão pormenorizada da cor, da composição, textura, relevo e luz das suas pinturas. De seguida, decidiu largar a típica pintura em cavalete, e utilizou a tela esticada no chão. A isto chama-se <i>all over</i>. Com a tela no chão atirava tinta e com isso abandonava o tradicional pincel. A pintura no chão favorecia uma maior mobilidade corporal, permitindo o acesso aos quatro cantos da tela e estar dentro dela, sentindo-a.",
				"Com Pollock nasce a pintura de acção <i>action painting</i>, onde o movimento, velocidade, e intensidade tomam a devida importância, para obter o resultado pretendido. Estes são tópicos primordiais para o minucioso trabalho do pintor. É aqui onde a questão da temporalidade se torna crucial para as suas pinturas, pois existe uma exploração espácio-temporal até aqui nunca tinha sido tão explorada, no mundo da pintura. Foi em 1947, que ocorreu esta mudança de conteúdo temático, e que se começou a repetir um padrão típico nas obras de Pollock, baseado no <i>dripping</i>. Cada gota de tinta ganhava um significado muito próprio e muito privado. Há quem não compreenda a intensidade de cada <i>drop</i>, e é certo que ninguém entenderá tão bem como ele entendia. De certa forma, as suas pinturas acarretam uma energia dinâmica que não nos permite ficar indiferentes a tais preciosidades.",
				"Pollock é o eterno pintor da melancolia. Porém, apesar das suas crises depressivas e existenciais, as suas telas manifestavam, por vezes, júbilo, contentamento e liberdade. Tudo relacionado com demonstrações do foro intimo com exclusão de factos exteriores. Era criada uma espécie de comunicação interna entre a viabilidade da arte e a viabilidade da vida."
			],
			obras:[
				{
					titl:"The She Wolf", ano:1943, imag:"jpo01.jpg",
					texto:"<i>The She Wolf</i> é uma das obras mais conhecidas de Jackson no período pré-gotejamento (pre-dripping). Apareceu na sua primeira exposição individual em 1943 e, no ano seguinte, foi comprado pelo Museu de Arte Moderna, tornando-se na primeira pintura de Pollock a entrar numa coleção do museu. Embora Pollock nunca tenha confirmado isso, muitos pensam que a pintura é baseada na lendária mãe lobo de Rômulo e Remo, os gêmeos que, segundo um mito, fundaram Roma. <i>The She Wolf</i> é considerado uma pintura importante no desenvolvimento da carreira artística de Pollock e um dos melhores exemplos de seu amor pela abstração de forma livre."
				},
				{
					titl:"Mural", ano:1943, imag:"jpo02.jpg",
					texto:"<i>Mural</i> foi o trabalho inovador de Jackson Pollock, que marcou um ponto de viragem em sua carreira, não só aumentando a sua reputação, mas também dando uma nova dimensão à sua arte. Pintado numa uma tela de 6,0 por 2,4 metros, foi sua primeira pintura realmente grande e uma das maiores que ele já fez. O seu tamanho, a abstração e o estilo prepararam o palco para as suas obras posteriores. O crítico de arte Clement Greenberg disse que ter comtemplado o <i> Mural</i> o fez perceber que <i>Jackson foi o maior pintor que este país já produziu</i>."
				},
				{
					titl:"Full Fathom Five", ano:1947, imag:"jpo03.jpg",
					texto:"<i>Full Fathom Five</i> é uma das primeiras obras-primas da técnica de gotejamento (dripping) de Pollock. Ele criou as suas pinturas mais famosas durante o período de gotejamento (dripping) que durou de 1947 a 1950. A pintura por gotejamento (dripping) é uma forma de arte abstrata na qual a tinta é gotejada ou derramada na tela, em vez de ser cuidadosamente aplicada. Pollock esteve entre os pioneiros da técnica de gotejamento (dripping), devido ao que a revista TIME o apelidou de <i>Jack the Dripper</i>."
				},
				{
					titl:"Number 5", ano:1948, imag:"jpo04.jpg",
					texto:"Trata-se da mais famosa e mais valiosa a pintura de Jackson Pollock. Em novembro de 2006, foi recorde mundial de maior preço pago por uma pintura quando foi vendida a um comprador anónimo por 140 milhões de dólares. Em outubro de 2015, ocupava o quinto lugar na lista das pinturas mais caras já vendidas. Esta pintura é considerada como um dos maiores monumentos ao Expressionismo Abstrato."
				},
				{
					titl:"Number 30", ano:1950, imag:"jpo05.jpg",
					texto:"1950 foi o ano de ouro para Jackson Pollock. Foi uma época em que ele estava no seu mais alto nível artístico e tinha dominado a técnica de gotejamento (dripping). Surpreendentemente, ele abandonou o estilo de gotejamento (dripping) no ano seguinte. O <i>Autumn Rhythm</i>, que foi originalmente intitulado <i>Number 30</i>, é uma de suas várias obras-primas do período de gotejamento (dripping). A pintura consiste em padrões caóticos de tinta preta, branca e castanha e é conhecida por não ter nenhum ponto focal, tornando-a igualmente significativa."
				},
				{
					titl:"Number 1", ano:1950, imag:"jpo06.jpg",
					texto:"Considerada pelos críticos de arte como uma das pinturas mais importantes de Pollock, este quadro mostra o génio do artista na sua pintura. Os físicos estudaram as obras de arte de Pollock na perspetiva dos fractais, que ocorrem naturalmente no caos. As suas pinturas dos anos 50 do século passado, como como é o caso desta, eram mais caóticas que suas obras anteriores e descobriu-se que, quanto mais caóticas elas se tornavam, mais se assemelhavam a fractais naturais."
				},
				{
					titl:"Number 31", ano:1950, imag:"jpo07.jpg",
					texto:"Este quadro foi pintado numa época em que Pollock já dominava a técnica de gotejamento (dripping) pela qual ele é mais conhecido. Ele foi pintado com a tela no chão, como era a norma para as pinturas de Pollock e está entre as maiores obras já criadas pelo artista. Os apreciadores de Pollock costumam referir este trabalho como a prova da extraordinária habilidade e destreza técnica do artista. É considerado por alguns como a maior pintura por gotejamento (dripping) de Pollock."
				},
				{
					titl:"Number 11", ano:1952, imag:"jpo08.jpg",
					texto:"Foi em 1954 que esta obra, de 1952, recebeu pela primeira vez o título <i>Pólos Azuis</i>, nome pelo qual é famoso hoje em dia. No entanto, alguns, incluindo o historiador de arte Dennis Phillips, acham que este novo título presta mau serviço à pintura porque induz o espectador a concentrar-se nos pólos azuis e a perder muito do resto. Esta obra foi comprada pela National Gallery of Australia em 1973 por 1,3 milhões de dólares americanos, o que, à altura, constituiu um recorde mundial para uma pintura americana contemporânea. Jornais na Austrália criticaram a compra e desencadearam um escândalo político que resultou em muita discussão pública sobre a pintura moderna. Hoje, o Blue Poles é uma das principais pinturas da coleção da National Gallery of Australia e a sua compra é hoje considerada um golpe de mestre. É um dos melhores trabalhos de Pollock e sua fama multiplicou-se devido ao seu lugar na história australiana."
				},
				{
					titl:"Convergence", ano:1952, imag:"jpo09.jpg",
					texto:"<i>Convergence</i> é uma das pinturas mais ambiciosas de Pollock. É conhecida pelo seu brilho visual e por evocar emoções profundas no espectador. Embora os trabalhos de Jackson permaneçam difíceis de decifrar até mesmo por especialistas em arte, as suas pinturas são consideradas manifestações de liberdade de expressão. <i>Convergence</i>, é um importante exemplo nesse sentido e continua a ser uma das suas obras-primas mais célebres."
				},
				{
					titl:"The Deep", ano:1953, imag:"jpo10.jpg",
					texto:"Principalmente feito em preto e branco com algumas partículas de amarelo e de azul claro, <i>The Deep</i> é uma das obras mais famosas de Pollock após os gloriosos anos 1947-1950. É um trabalho importante do Expressionismo Abstrato. Os espectadores e críticos de arte discorrem sobre várias interpretações filosóficas desta pintura. O nome da pintura aumentou o seu mistério com várias deduções, como se ela representasse a profundidade em que reside o verdadeiro <i>eu</i> que cada pessoa esconde em si, mas que muito teme ter que enfrentá-lo."
				}
			]
		},
		{//3-Franz Kline
			nome:"Franz Kline", nacion:"americana",
			dataNasc:"19100523", localNasc:"Wilkes-Barre, Pennsylvania, EUA",
			dataMorte:"19620513", localMorte:"Nova Iorque, EUA",
			foto:"FranzKline.jpg",
			texto:[
				"Franz Kline é uma figura chave do Expressionismo Abstrato, bem conhecido pelas suas pinturas em preto e branco, e fez uma contribuição poderosa para o movimento de vanguarda. Nascido na Pensilvânia em 1910, Kline desenvolveu um interesse pela ilustração durante o ensino médio e continuou a sua educação como desenhista na Universidade de Boston, entre 1931 e 1935. Continuou os seus estudos em Londres, retornando aos Estados Unidos em 1939.",
				"Kline mudou-se então para Nova Iorque, onde foi feita a sua carreira. O seu domínio precoce do desenho, incluindo a caricatura, conferiu-lhe a sintonia com a essência abstrata da linha. Trabalhando com óleo, o estilo de Kline foi desenvolvido a partir de obras figurativas e representacionais para composições emblemáticas e caligráficas, onde as formas rapidamente se tornaram marcas escovadas. O ambiente de Nova Iorque inspirou Kline; os seus esboços, óleos e murais pintados em 1940 para o Cedar Bar em Greenwich Village (um popular ponto de encontro dos expressionistas abstratos) revelam o seu interesse em buscar um equivalente pictórico dos ritmos dinâmicos da cidade, em pinceladas rápidas, enérgicas e largas.",
				"Observador atento da pintura de Willem De Kooning e de Robert Motherwell, em 1946, Kline começou a generalizar os seus temas, criando composições que enfatizavam a linha caligráfica. Estudos em tinta sobre papel reforçaram o gosto do artista por uma paleta reduzida a preto e branco. Quando o seu amigo De Kooning ampliou esses esboços, em 1948, com a ajuda de um projetor Bell-Opticon, proporcionou a Kline apreciar os seus traços ampliados em poderosos gestos abstratos. Isso confirmou a sua consciência do potencial dramático e expressivo do esboço, mas projetado numa escala monumental. Usando uma paleta limitada de preto em linhas grossas e ásperas pintadas com pincéis de pintor de paredes grandes em solo branco, Kline atingiu a maturidade do seu estilo próprio em 1950. Nesse mesmo ano, Kline garantiu a sua primeira exposição individual na Charles Egan Gallery em Nova Iorque, exibindo obras com pinceladas negras enormes em bandas e cunhas negrito, dominando as grandes telas brancas. ",
				"Embora alguns críticos acreditassem que os padrões da grade negra de Kline eram improvisações ampliadas de signos e símbolos encontrados na caligrafia oriental, o artista negou qualquer influência do Oriente no desenvolvimento de suas abstrações e enfatizou o seu fascínio pela beleza urbana de Nova Iorque. Embora Kline seja identificado principalmente com os seus trabalhos em preto e branco, ele também era um colorista distinto; os anos em preto e branco do pós-guerra deram lugar a explorações em cores. Os trabalhos de Kline tiveram um papel importante na definição do expressionismo abstrato, e o sucesso de seu estilo maduro influenciou muitos expressionistas abstratos de segunda geração.",
				"Durante a década de 1950, Kline ensinou em várias instituições, incluindo o Black Mountain College, na Carolina do Norte, e o The Pratt Institute, em Brooklyn. Em 1958, ele foi incluído na principal exposição do Museu de Arte Moderna, <i>The New American Painting</i>, que percorreu oito cidades europeias. O seu trabalho faz parte de importantes coleções públicas e privadas nos Estados Unidos, Canadá, Europa e Japão. A morte tragicamente prematura de Kline de uma doença cardíaca reumática, em 1962, deixou incerta a continuação da sua visão artística, porém, ele continua sendo um reconhecido mestre do Expressionismo Abstrato."
			],
			obras:[
				{
					titl:"Chief", ano:1950, imag:"fkl01.jpg",
					texto:"Os comentários dos críticos sobre as imagens do espetáculo inovador da pintura de Kline, em 1950, estabeleceram o padrão para posteriores revisões com a sua variedade de analogias. <i>Chief</i> era o nome de uma locomotiva que Kline recordava da sua infância, e é possível ler a imagem como uma reminiscência sensorial da sua potência, do seu som e da máquina a vapor. Alguns também acreditavam que a obsessão do artista com o preto estava ligada à sua infância passada numa comunidade de mineração de carvão dominada pela indústria pesada. Muitos já observaram, no entanto, que as formas nessas abstrações iniciais parecem ter evoluído a partir dos desenhos de Kline sobre a sua esposa, Elizabeth. Ele fez vários esboços dela sentada numa cadeira de balanço nos anos em que ela começou a sucumbir à doença mental; as formas circulares em <i>Chief</i> são comparadas com os círculos em branco representando o rosto dela nos desenhos."
				},
				{
					titl:"Painting No. 7", ano:1952, imag:"fkl02.jpg",
					texto:"Ao contrário de seus colegas Pollock e De Kooning, Kline nunca experimentou elementos figurativos no seu trabalho maduro. Este é um bom exemplo dos seus trabalhos em preto e branco. A geometria rígida das linhas pretas amplas define a composição, talvez manifestando a sua reconsideração das pinturas icónicas de quadrados de Kazimir Malevich."
				},
				{
					titl:"Black Reflection", ano:1956, imag:"fkl03.jpg",
					texto:"Black Reflection é um exemplo das primeiras tentativas de Kline de introduzir a cor de volta às suas obras. O tratamento da cor nesta composição pode estar relacionado com as pinturas contemporâneas de Willem de Kooning e Hans Hofmann. O ponto focal desta imagem é a forma negra que Kline já tinha usado anteriormente em outras composições. Este fato atesta ainda mais a cuidadosa consideração que os artistas da <i>Action Painting</i> dedicaram às formas pictóricas nas suas composições."
				},
				{
					titl:"Mahoning", ano:1956, imag:"fkl04.jpg",
					texto:"O que faz com que o preto e branco de Kline seja tão especial é que eles não são apenas consistentes, alguns até os chamam de pinceladas pretas violentas, agressivas em telas brancas. Os dois elementos são essenciais para a existência um do outro. Em vez de se concentrar nas áreas brancas como o “espaço negativo”, ele as pintou em ordem alternada com igual consideração. Kline criaria judiciosamente estudos de pequena escala para cada uma de suas pinturas finais sobre tela. Ele costumava pintá-los em jornais do tamanho de um cartão postal, trabalhando e refazendo cada gesto para obter o equilíbrio perfeito. Então, uma vez terminada a composição, Kline projetou-a em uma tela grande e repetiu o processo, com toda a sua intensidade."
				},
				{
					titl:"Four Square", ano:1956, imag:"fkl05.jpg",
					texto:"É um exemplo da experimentação de Kline com composições angulares. Embora aparentemente estruturado na sua rigidez composicional, <i>Four Square</i> é um bom exemplo de sua abordagem gestual à pintura. O espectador é levado a refletir sobre a tela, visto como um close-up de um símbolo linguístico ou, talvez, um conjunto de janelas abertas. Neste trabalho, Kline também está tentando construir uma composição abstrata tridimensional, enquanto a maioria dos expressionistas abstratos preferiu o tratamento bidimensional da superfície pictórica. Kline alcança o efeito visual de profundidade através de justaposições energéticas de linhas verticais e horizontais e sua sobreposição diagonal."
				},
				{
					titl:"Meryon", ano:1960, imag:"fkl06.jpg",
					texto:"Existe um forte sentido arquitetónico em sua composição desta obra. A inspiração foi possivelmente uma gravação de uma torre do relógio do artista francês do século XIX Charles Meryon. Novamente, Kline representa não o objeto em si, mas a sua visão dele. Aparentemente espontânea no seu arranjo, esta composição foi concebida através de uma série de estudos preliminares, lançando uma nova luz sobre a natureza da sua técnica gestual."
				},
				{
					titl:"Probst I", ano:1960, imag:"fkl07.jpg",
					texto:"Esta obra refere-se a Jack Probst, um colega artista que morava perto de Kline em Greenwich Village. À primeira vista, essa composição é típica do seu trabalho em preto e branco. No entanto, há mais cores presentes nesta tela. Há salpicos de salmão amarelo e pálido que iluminam a solidez de formas negras e torcidas, criando efeitos luminosos e quentes. <i>Probst I</i> é um exemplo do trabalho tardio de Kline, onde ele voltou a empregar uma paleta mais ampla."
				}
			]
		},
		{//4-Mark Rothko 
			nome:"Mark Rothko", nacion:"americana",
			dataNasc:"19030925", localNasc:"Daugavpils, Letónia",
			dataMorte:"19700225", localMorte:"Nova Iorque, EUA",
			foto:"MarkRothko.jpg",
			texto:[
				"Embora tenha nascido na Letónia, Mark Rothko é um dos artistas americanos mais conhecidos, pelas peças expressionistas abstratas que ele criou durante o curso de sua carreira. Nascido em 1903, ele e a sua família emigraram para os EUA quando ele tinha 10 anos de idade. Algumas das obras pelas quais ele é mais conhecido são imagens que apresentavam grandes blocos de cores luminosas. Ele também é mais conhecido como um dos melhores pintores da Escola de Abstração de Nova Iorque, pelas formas, figuras e grande criação de cores que ele entregou, nas muitas pinturas que ele criou. As impressões de Mark Rothko são atualmente algumas das mais procuradas por consumidores de reproduções de arte em todo o mundo, destacando como a reputação desse artista se espalhou através de fronteiras geográficas e sociais.",
				"Em 1921, Mark Rothko frequentou a Universidade de Yale, com um projeto de estudos de obter um diploma, ou em engenharia, ou em direito. Porém acabou por abandonar ambas as rotas e escolheu uma carreira diferente. Depois de deixar Yale, Rothko mudou-se para Nova Iorque, como ele disse, <i>para vagabundear e passar um pouco de fome</i>. Nos seguintes, ele teve vários empregos e estudou algum tempo na Art Students League, sob o comando de Max Weber, um dos únicos professores que tinham conhecimento e entusiasmo pelo modernismo europeu. As primeiras pinturas de Mark Rothko foram orientadas para temas sociais e contêm conotações expressionistas e surrealistas. Refletiam a influência de Weber e também de artistas modernos, como Manet, Paul Cezanne e Picasso e mostraram o seu potencial como artista. As cenas urbanas e as paisagens e a aplicação grosseira da pintura mostraram um lado expressivo da arte que ele criaria mais tarde, e as características que o tornaram mais conhecido durante o curso de sua carreira como artista.",
				"Em meados da década de 1930, Mark Rothko juntou-se a um grupo de pintores em Nova Iorque, conhecido como <i>Os Dez</i>. Este grupo dedicava-se a trabalhos modernistas e, depois, ao trabalho abstrato que se seguiria e que foi extremamente popular neste período e durante várias décadas nos EUA. Faziam parte desse grupo, além de Mark Rothko, outros artistas, como, para citar alguns, Adolph Gottlieb, Louis Harris, Ben-Zion e Joseph Salmon.",
				"Durante a década de 1940, Mark Rothko adotou uma abordagem da arte, na qual ele queria mudar o que o público americano passara a conhecer como arte abstrata. Ele procurava uma nova linguagem para mostrar as diferentes visões americanas durante a guerra. Durante este período, muitas das peças que ele criou foram simbólicas da guerra e da vida americana dessa época. As características simbólicas crescentes incluíam formas biomórficas que foram usadas na sua arte, e foram influenciadas por imagens surrealistas e por artistas que estavam surgindo durante este período.",
				"No final dos anos 1940 e início dos anos 50, Mark Rothko criou algumas das peças pelas quais ele é mais conhecido na sua carreira. Muitas das obras que ele mostrou durante esse período mostraram pinceladas grandes e escuras, grandes blocos de cor e uma vasta variedade de lavagens. Criou peças grandes e contemplativas que simbolizavam, tanto a vida americana durante esse período, como as mudanças no mundo da arte e o trabalho abstrato que is surgindo, à medida que a sua carreira progredia.",
				"No final da década de 1950, Mark Rothko adotou outra abordagem para as suas obras. Eram frequentemente usadas cores e tons mais escuros e texturas mais ricas. Durante esse período, o artista também passou um bom tempo focado num trabalho que ele criaria para uma capela (Rothko Chapel) localizada em Houston. Isso não apenas demonstrou a crença numa arte espiritual, mas também a sua religiosidade. Mostrou os laços espirituais e emocionais entre a arte e a fé.",
				"Ao longo de sua vida, Mark Rothko sofreu com profundos episódios de depressão, e em 1970 ele tirou a própria vida, como muitos outros artistas tinham feito antes dele. Mas, mesmo com uma carreira mais curta do que muitos outros artistas no mundo abstrato, ele teve sucesso com os trabalhos que criou durante o curso de sua carreira. Quando faleceu, Mark Rothko teve uma exposição exclusiva, com algumas de suas peças mais famosas, no Museu Museu de Arte Moderna de Nova Iorque. Mark Rothko também foi visto como um dos principais artistas americanos, no mundo da pintura abstrata. Ele fez a transição para a arte abstrata e para novas abordagens modernas, que permaneceriam em vigor por várias décadas."
			],
			obras:[
				{
					titl:"Entrance to Subway", ano:1938, imag:"mro01.jpg",
					texto:"Este trabalho figurativo inicial demonstra o interesse de Rothko pela vida urbana contemporânea. As características arquitetónicas da estação são recriadas superficialmente, incluindo as catracas e a letra N na parede. Embora o humor das imagens seja suavizado pela influência do impressionismo, reflete muitos dos sentimentos do artista em relação à cidade moderna. A cidade de Nova Iorque era considerada desalmada e desumana, e algo disso é transmitido aqui pelas características anónimas e difusamente reproduzidas das figuras."
				},
				{
					titl:"Oedipus", ano:1944, imag:"mro02.jpg",
					texto:"A mitologia grega era um tema importante do trabalho de Rothko no início dos anos 1940. Édipo era o assassino do seu pai e o amante da sua mãe. Sua história inspirou artistas e psicólogos. Para Rothko, Édipo encarna a vítima do orgulho e da paixão, que o artista acreditava estar no centro da natureza destrutiva do homem. Como em outras obras representacionais da época, Rothko desmembrou e recombinou as suas figuras tão intrincadamente que elas se tornaram uma única massa de conglomerados humanos. Dessa maneira, Rothko procurou sugerir como a humanidade está unida pela tragédia. As figuras aparecem estranhamente amontoadas no canto de uma estranha sala. O padrão em ziguezague azul e verde aparece em várias de suas imagens mitológicas. Como disse Rothko, <i>Se os nossos títulos recordam os mitos conhecidos da antiguidade, nós usamo-los novamente porque eles são os símbolos eternos sobre os quais devemos incidir para exprimir idéias psicológicas básicas que dizem sobre algo real e existente em nós mesmos</i>."
				},
				{
					titl:"Slow Swirl at the Edge of the Sea", ano:1944, imag:"mro03.jpg",
					texto:"É um exemplo representativo do período surrealista de Rothko. A influência de Miró é clara. Toda a composição de cores suaves, estranhas figuras translúcidas, linhas horizontais, ângulos e redemoinhos, criam uma imagem vibrante mas velada de uma obscura paisagem primitiva. Pintada enquanto Rothko cortejava Mary Beistel, que se tornaria na sua segunda esposa, esta cena caprichosa também pode ser interpretada como um romance dentro de um mundo mítico e mágico, onde as figuras estão apreciando o oceano sobre um colorido amanhecer estampado no horizonte."
				},
				{
					titl:"No. 9", ano:1947, imag:"mro04.jpg",
					texto:"É um dos onze quadros que Rothko apresentou na Betty Parsons Gallery na primavera de 1949. Tendo deixado para trás as figuras e as paisagens do seu trabalho anterior, os <i>multiformes</i>, dos quais este é um exemplo típico, apresentavam formas borradas criadas a partir de camadas de tinta. O trabalho antecipa o avanço de Rothko, a partir de 1949, para os chamados <i>seccionais</i>. Os vermelhos quentes, laranjas e amarelos deste quadro são interrompidos pela estranha massa negra que vem da esquerda, bem como os redemoinhos de azul na parte inferior. As bordas borradas, os blocos de cores separadas e os registros iniciais retangulares podem ser vistos, bem como algumas experiências com tamanho e escala. Longe de ser apenas formas abstratas, Rothko acreditava que esses motivos eram objetos imbuídos da sua força vital, <i>organismos com a paixão pela auto-expressão</i>."
				},
				{
					titl:"White Center (Yellow, Pink and Lavender on Rose)", ano:1950, imag:"mro05.jpg",
					texto:"Esta obra constitui a primeira manifestação séria do estilo multiforme de Mark Rothko, de vários blocos de cores complementares em camadas numa grande tela, em que Rothko continuou a simplificar os elementos de composição de suas pinturas. Em 1950, ele começou a dividir a tela em faixas horizontais de cor. Apesar da composição frontal e da ausência de ilusionismo espacial nesses trabalhos, as amplas faixas de cor aparecem simultaneamente a flutuar em frente ao plano da imagem e a fundir-se com o campo de cor sobre o qual elas são colocadas. Uma luminosidade resulta da estratificação repetida de finas lavagens de tinta, o que permite que algumas camadas inferiores se mostrem através das camadas superiores. Em cada obra desse período, Rothko buscava subtis variações de proporção e cor, conseguindo uma ampla gama de emoções e de humores. Em 2007, o quadro foi comprado por 72,84 milhões de dólares, pela família real do Qatar."
				},
				{
					titl:"No.1 (Royal Red and Blue)", ano:1954, imag:"mro06.jpg",
					texto:"Este quadro, pintado em 1954, uma época considerada por muitos como o auge da veia criativa de Rothko, é considerado como uma das grandes realizações da pintura abstrata de Rothko. A aura estonteante da brilhante superfície vermelha e laranja é soberbamente contra-atacada pela pilha azul de intensa vividez na sua base, dando ao espectador a sensação de que a tela é iluminada por dentro. Esta pintura é um marco fundamental na fase madura da expressão artística de Rothko, na qual ele foi pioneiro em territórios sem precedentes de um espetacular derramamento de inovação."
				},
				{
					titl:"Untitled (Yellow and Blue)", ano:1954, imag:"mro07.jpg",
					texto:"No auge da criatividade simplificadora de Rothko no período dos chamados trabalhos <i>seccionais</i>, este quadro surpreende-nos uma aurora brilhante de luz e de cor cintilante e confronta-nos com a intensidade filosófica do seu criador, onde ele encenou algumas das mais comoventes, transcendentes e simplesmente impressionantes uniões já realizadas entre o material e o suporte, na grande tradição de tinta a óleo sobre tela. O quadro foi vendido a um anónimo por 46,5 milhões de dólares num leilão da Sotheby's em Nova Iorque."
				},
				{
					titl:"Four Darks in Red", ano:1958, imag:"mro08.jpg",
					texto:"É uma das dez obras de Rothko exibidas em 1969 na Galeria Sidney Janis. Com a sua paleta escura e restrita, a pintura exemplifica a gravitação do período tardio de Rothko em direção aos vermelhos e castanhos. Nesta obra Rothko estabeleceu um protótipo para a paleta roxo ou vermelho escuro, castanho e preto e para a composição horizontal que ele usaria mais tarde em diversos outros trabalhos, como a <i>Rothko Chapel</i>, por exemplo. Rothko acreditava que os retângulos apenas ofereciam uma nova maneira de representar as presenças ou espíritos que ele tentava capturar e imaginou uma espécie de comunhão direta entre ele e o espectador, em que este seria tocado por uma espiritualidade mais elevada."
				},
				{
					titl:"Rothko Chapel", ano:1965, imag:"mro09.jpg",
					texto:"Situada no campus da St. Thomas Catholic University, a capela Rothko foi financiada por John e Dominique de Menil e contém catorze pinturas murais de Rothko. Existem três trípticos e cinco trabalhos individuais. Todas estas pinturas são em tons de roxo ou vermelho escuro, castanho e preto e são de grande escala. Rothko trabalhou em estreita colaboração com os arquitetos, tendo o controlo quase completo sobre a forma do edifício e do seu ambiente interior de meditação. A escuridão das obras pode ser vista como melancólica e expressiva do humor de Rothko nos seus últimos anos. Infeizmente para ele, não viveu para assistir à inauguração da Capela."
				},
				{
					titl:"Untitled, Black on Gray", ano:1969, imag:"mro10.jpg",
					texto:"Rothko juntou muitos conhecidos seus da elite mundial da arte nova-iorquina no seu estúdio para mostrar o seu último quadro, que marcaria a sua última série de pinturas, a <i>Black on Grays</i>. O evento foi principalmente envolto em silêncio, porque alguns pensaram que estas eram premonições de sua morte. Outros achavam que, com a prevalência de imagens lunares na cultura popular, eram interpretações de paisagens lunares. Outros achavam que eram pinturas de visões noturnas. O grupo de convidados não levava a sério a apresentação, o que era devastador para Rothko, pois, além do mais, afirmavam que só ele sentia o mundo interior das suas pinturas e que, assim, elas eram apenas compreensíveis para ele sozinho. Os <i>Black on Grays</i> foram pintados diretamente sobre tela branca e não tinham a pintura base normal que Rothko gostava de ter por baixo. Trabalhando apenas em dois registos, ele restringiu severamente as cores e reduziu a tela a um tamanho mais acessível e intimista. O contraste extremo da luz e da escuridão evoca uma tristeza que se desenrola como um drama psicológico, tanto mítico como trágico."
				}
			]
		},
		{//5-Adolph Gottlieb
			nome:"Adolph Gottlieb", nacion:"americana",
			dataNasc:"19030314", localNasc:"Nova Iorque, EUA",
			dataMorte:"19740304", localMorte:"Nova Iorque, EUA",
			foto:"AdolphGottlieb.jpg",
			texto:[
				"Adolph Gottlieb foi um proeminente pintor americano e membro da primeira geração de expressionistas abstratos. Através de um uso idiossincrático da abstração com pictogramas e símbolos mitológicos, as suas obras alcançaram uma intensidade emocional através da cor e da linha. <i>Hoje, quando as nossas aspirações foram reduzidas a uma tentativa desesperada de escapar do mal e os nossos tempos estão desarticulados, as nossas imagens obsessivas, subterrâneas e pictográficas são a expressão da neurose que é a nossa realidade</i>, refletiu ele certa vez. <i>Na minha opinião, a chamada abstração não é abstração. Pelo contrário, é o realismo do nosso tempo</i>.",
				"Nascido em 14 de março de 1904, em Nova Iorque. Após abandonar o ensino médio em 1919, Gottlieb participou da Art Students League brevemente antes de partir para a Europa em 1921. Ele viajou para Viena, Berlim, Dresden e Munique, tendo participado em aulas de desenho ao vivo em Paris. Logo após seu retorno em 1922, ele estudou na Art Students League de Nova Iorque, onde conviveu com um grupo de pintores que incluía Mark Rothko, Lou Schanker, Barnett Newman, e John Graham. Gottlieb, tal como Rothko, também começou a produzir obras influenciadas pela figuração estilizada de Milton Avery. Interessado em Surrealismo, o trabalho de Gottlieb tornou-se mais abstrato, pois incorporou na sua prática o desenho automático e as teorias psicológicas de Sigmund Freud e Carl Jung.",
				"Gottlieb fez sua primeira apresentação individual na Galeria Dudensing em 1930. Em 1935, tornou-se um dos membros fundadores do <i>The Ten</i>, um grupo de artistas que se opunha ao estreito realismo dos pintores regionalistas contemporâneos. Depois de outra viagem à Europa em 1935, Gottlieb trabalhou num projeto federal de artes entre 1936 e 1937. Como muitos de seus colegas, ele era politicamente ativo, juntou-se à Artist's Union em 1936 e tornou-se membro fundador do American Artist's Congress nesse mesmo ano e da Federação de Pintores e Escultores Modernos em 1940.",
				"Durante uma viagem ao Arizona (1937-1938), ele viu exemplos de murais arcaicos em regiões índias, o que, conjuntamente com a influência emergente do surrealismo em Nova York durante a Segunda Guerra Mundial o levou a repensar sua arte. Em 1941, começou a fazer os seus pictogramas, imagens compostas de formas inventadas e misteriosas, dispostas numa grade no plano da imagem, sugerindo a comunicação simbólica das culturas pré-históricas. Os pictogramas de Gottlieb também demonstram seu fascínio pela arte primitiva que o levou a colecionar arte africana, a partir do final dos anos 1930 e a frequentar regularmente exposições de arte africana, indígena e pré-histórica no Museu de Arte Moderna. Ele via a arte primitiva como a expressão direta e incisiva de forças desconhecidas e uma fonte relevante de significado no meio do tumulto e da injustiça dos eventos da Segunda Guerra Mundial.",
				"Em 1947, Gottlieb entrou para a Kootz Gallery e associou-se com Robert Motherwell e Hans Hofmann. Dividindo seu tempo entre Nova Iorque e Provincetown, ele participou, no início dos anos 50, em discussões e fóruns sobre desenvolvimentos artísticos americanos. Nas suas pinturas dos anos 50 e 60, que apresentavam formas abstratas em grande escala flutuando no plano do quadro, Gottlieb revelou o seu crescente interesse pela pintura em cores primárias e pelo simbolismo abstrato.",
				"Na década de 1960, ele começou a produzir algumas de suas obras mais famosas, coletivamente conhecidas como <i>Burst Paintings</i>, cujo motivo comum é um círculo parecido com o sol que paira sobre marcas caligráficas. Várias comissões e prémios, incluindo uma retrospectiva em 1968 realizada simultaneamente nos museus Whitney e Guggenheim em Nova Iorque, destacaram o fim da carreira de Gottlieb. Depois de sofrer um derrame cerebral em 1971, Gottlieb morreu a 4 de março de 1974, em Nova Iorque."
			],
			obras:[
				{
					titl:"Pictograph", ano:1946, imag:"agt01.jpg",
					texto:"Esta pintura consiste em uma estrutura de grade solta dentro da qual são fragmentadas e sobrepostas formas femininas que foram abstraídas em linhas e formas planas. Espirais adicionais e formas geométricas, assim como rabiscos e uma flecha (que podem sugerir elementos masculinos ou o caminho que leva para fora da estrutura e do confinamento) preenchem o restante espaço da imagem. Os estudiosos frequentemente apontam para as cores rosa e castanho como a influência remanescente das cores que o artista absorveu durante sua visita ao Arizona, embora se possa facilmente apontar para influências de Willem de Kooning, ou de André Masson, por exemplo. Defensor da honestidade das duas dimensões, contra a pretensa ilusão da profundidade (terceira dimensão) no suporte plano, Gottlieb afirmava que, embora a abstração geométrica reduzisse a pintura a um exercício puramente intelectual, essa arte deveria ser uma expressão do pensamento e da experiência humana. Assim, nesta pintura há uma textura macia e pictórica na superfície que humaniza a geometria, comunicando ao observador o significado da nossa própria existência pessoal dentro da humanidade, como um todo."
				},
				{
					titl:"Vigil", ano:1948, imag:"agt02.jpg",
					texto:"Esta pintura é típica das pinturas gráficas de Gottlieb, com a compartimentalização geométrica do espaço plano e o uso de sinais e símbolos aparentemente míticos. Embora os símbolos pareçam arcaicos, Gottlieb inventou a maioria dos seus símbolos, evitando cuidadosamente precedentes e narrativas históricas específicas (embora muitos de seus títulos se refiram à mitologia grega). Assim, Gottlieb pretendia que s suas imagens transcendessem as barreiras da cultura, do tempo e da linguagem. Ele estava interessado na psicologia de Sigmund Freud e Carl Jung, acreditando que os símbolos universais têm o poder de destravar o inconsciente coletivo dos espectadores. Este quadro confronta-nos diretamente com vários rostos semelhantes a máscaras que sugerem fontes não-ocidentais (africanas, por exemplo) contra um fundo escuro que sugere a noite, e talvez a necessidade de estar atento. Os olhos desencarnados podem funcionar como talismãs, ou, no contexto do mito de Édipo sobre o qual Gottlieb pintou uma série, eles também podem referir-se à cegueira. O tema da visão versus cegueira é enfatizado pelo fundo escuro e, simultaneamente, aumenta o significado do título, sugerindo que a vigilância neutraliza a cegueira. As linhas adicionadas e a geometria ajudam a unificar a imagem, mapeando um possível percurso de ação para o espectador."
				},
				{
					titl:"Flotsam at Noon1", ano:1952, imag:"agt03.jpg",
					texto:"Gottlieb começou sua série <i>Imaginary Landscapes</i> em 1952. Aqui, ele explorou simbolicamente a questão da profundidade, criando uma tela dividida por um horizonte oblíquo aparente e sem qualquer ilusão de espaço. Vestígios dos seus pictogramas, incluindo escrita automática e figuras, emergem dos tons terrosos da porção inferior da imagem em contraste com o bloco sólido de cor habitado por formas ovóides e retangulares no topo da composição. A ausência da estrutura de grade dos trabalhos anteriores de Gottlieb atrai novo foco para colorir e formar símbolos. Essa mudança estilística é reforçada pela adição às <i>Imaginary Landscapes</i> de tons e cores mais brilhantes do que as pictografias anteriores. Tanto a expressão quanto o conteúdo estão implícitos na natureza frágil das confusas pictografias embutidas na parte figurativa da imagem, enquanto as formas pairam na parte superior, distantes, mas insistentes."
				},
				{
					titl:"Unstill Life III", ano:1956, imag:"agt04.jpg",
					texto:"Trata-se de um terceiro trabalho de uma mesma série. Pode-se ver como a pintura se relaciona com a obra anterior de Gottlieb, com os seus elementos pictográficos e os vestígios de uma grade. Aqui, Gottlieb emprega um grau intransigente de abstração e modernidade com a sua paleta de negros, cinzas e vermelhos. Além disso, o trabalho cada vez mais abstrato e gestual da imagem dentro das enfáticas linhas divisórias agora é lido mais ardentemente na superfície como uma espécie de matriz em oposição a uma grade. O espaço negativo também entra mais em jogo para contrastar e equilibrar as seções internas da composição da pintura. O movimento e a pulsação da pintura contrastam nitidamente com a aparente planicidade do desenho da pintura, refletindo o título da série."
				},
				{
					titl:"Mist", ano:1961, imag:"agt05.jpg",
					texto:"As pinturas de Gottlieb sofreram uma transformação significativa nos anos 50, quando ele abandonou a grade, simplificou as suas formas e aumentou muito a escala das suas telas. Nos <i>Bursts</i> verticais que ele iniciou em 1957, dos quais este trabalho é um exemplo, um disco difuso na zona superior paira sobre uma explosão de pinceladas caligráficas na zona inferior. Apesar da sua abstração, os <i>Bursts</i> evocam uma série de associações, desde paisagens e formas cósmicas até nuvens de cogumelos nucleares. Embora, à primeira vista, essas obras possam parecer totalmente não relacionadas com os pictogramas anteriores, ambas as séries se baseiam na justaposição de formas e são caracterizadas por um dualismo subjacente."
				},
				{
					titl:"Blues", ano:1962, imag:"agt06.jpg",
					texto:"A partir de 1956, as monumentais pinturas <i>Burst</i> de Gottlieb desenvolveram-se a partir das <i>Imaginary Landscapes</i>, focando na simplificação do espaço e da cor da série anterior. Embora a paleta mais típica dessas pinturas seja de vermelhos e pretos, este quadro apresenta similarmente uma grande tela verticalmente orientada num campo de cor clara, interrompida apenas por um disco brilhante sobre uma forma solar distorcida de pinceladas grossas e gestuais escuras. A profundidade e o horizonte são completamente eliminados, fazendo com que a cor e a forma sejam o único foco do campo da imagem. As polaridades das cores e formas fornecem a chave para a imagem: abaixo, as linhas grossas que criam uma massa móvel, desordenada, não resolvida; acima, o brilho hipnotizante dos azuis pulsantes e celestes. Em 1962, na data desta pintura, Gottlieb falou sobre a qualidade emocional da cor no seu trabalho. Visualizando a pintura, fica-se impressionado com a gama de efeitos emocionais que o artista explora através da cor azul, progredindo para fora a partir do núcleo, o azul da composição desenvolve-se a partir de um signo subtil e misterioso para uma declaração intensa e vibrante."
				},
				{
					titl:"Burst", ano:1973, imag:"agt07.jpg",
					texto:"Pintado apenas um ano antes da morte de Gottlieb, este é um dos últimos quadros da série de pinturas de <i>Burst</i>. A forma alongada da imagem ecoa a composição vertical de suas pinturas anteriores, enfatizando o espaço vazio entre as porções inferior e superior da imagem. Uma zona horizontal bege e comprimida na parte inferior da composição serve de base para as marcas pretas e gestuais mais delicadas e complacentes, empurradas contra a borda inferior. Uma distância dolorosamente longa separa essa área inferior da órbita vermelha pairando no topo da composição, que lança um brilho cada vez mais rosado. Gottlieb achava que o espaço da imagem deveria funcionar como uma questão de escala e tamanho da pintura, como ele disse, <i>o espaço da imagem é o espaço com o qual somos confrontados, em relação ao nosso próprio tamanho</i>."
				}
			]
		},
		{//6-Philip Guston 
			nome:"Philip Guston", nacion:"canadense e americana",
			dataNasc:"19130727", localNasc:"Montreal, Canadá",
			dataMorte:"19800607", localMorte:"Woodstock, Nova Iorque, EUA",
			foto:"PhilipGuston.jpg",
			texto:[
				"Philip Guston, de nome original, Phillip Goldstein, foi pintor e gravador na <i>New York School</i>, um movimento de arte que incluía muitos expressionistas abstratos como Jackson Pollock e Willem de Kooning. Não sendo um pintor expressionista abstrato, <i>puro e duro</i>, manteve-se como membro ideológico do Expressionismo Abstrato e, no final da década de 1960, Guston ajudou a promover uma transição do Expressionismo Abstrato para o Neo-Expressionismo na pintura, abandonando a chamada <i>abstração pura</i> em favor de representações mais expressivas e caricaturadas de várias situações, símbolos e objetos pessoais.",
				"Guston ficou conhecido pelas suas pinturas em estilo <i>cartoon</i>, criadas no período posterior a 1968, com uma natureza existencial e lúgubre e com uma paleta limitada. Além disso, foi professor e conferencista em várias universidades e, por essa razão também é considerado por suas palavras e ensinamentos teóricos, coletados no livro <i>Philip Guston: Collected Writings, Lectures, and Conversations (Documents of Twentieth-Century Art)</i>.",
				"Philip Guston nasceu em 1913 em Montreal, sendo o mais novo de sete irmãos. Toda a família se mudou para Los Angeles quando ainda era criança. Os seus pais eram judeus ucranianos de Odessa que escaparam da perseguição quando se mudaram para o Canadá. Guston e a sua família estavam conscientes das atividades regulares da Ku Klux Klan contra judeus, negros e outros que ocorriam em toda a Califórnia. Em 1923, possivelmente devido à perseguição ou à dificuldade em obter rendimentos, o seu pai enforcou-se na cave da casa e foi o jovem Guston que encontrou o seu corpo.",
				"Guston começou a pintar em 1927, aos 14 anos, quando se matriculou no Los Angeles Manual Arts High School. A arte inicial de Guston era figurativa e representativa. A sua mãe apoiava as suas inclinações artísticas e muitas vezes faziam desenhos juntos numa pequena secretária, iluminada por uma lâmpada. Tanto ele como Jackson Pollock estudaram com Frederick John de St. Vrain Schwankovsky, um influente pintor e ilustrador, membro da Sociedade Teosófica, e contactaram com a arte moderna europeia, a filosofia oriental, a teosofia e a literatura mística. Durante o ensino médio, Guston e Jackson Pollock publicaram um artigo em oposição à ênfase do ensino médio sobre desportos em prejuízo da arte. Essas críticas levaram ambos a serem expulsos, mas Pollock acabou por voltar e formou-se.",
				"Para além de seu ensino médio e de uma bolsa de estudos de um ano no Otis Art Institute, em Los Angeles, Guston permaneceu como um artista, em grande parte autodidata. No Otis Art Institute, Guston sentia-se insatisfeito com a abordagem académica que o limitava a desenhar em moldes de gesso em vez do modelo ao vivo. Antes de deixar a escola, Guston passou uma noite no estúdio fazendo desenhos dos gessos figurativos espalhados pelo chão.",
				"Em 1931, Guston, com 18 anos, produziu um mural interno com Reuben Kadish em apoio ao esforço do John Reed Club de Los Angeles para angariar fundos para apoiar os réus no julgamento de Scottsboro Boys. Este mural foi então adulterado pelas forças policiais locais, conhecidas como Red Red Squads. A subsequente decisão do tribunal não considerou qualquer falha por parte da polícia de Los Angeles, apesar dos danos irreversíveis sofridos pelas diversas obras de arte. Isto marca apenas uma instância da corrupção política testemunhada por Guston, um tema que ele voltaria a pintar no seu estilo tardio.",
				"Em 1935 fixa-se em Nova Iorque, realizando murais para o WPA (Federal Arts Project / Works Progress Administration), e em 1941 parte para Iowa City, para ensinar na School of Art and Art History. Postas de parte as grandes encomendas, dedica-se a uma arte mais íntima e pessoal.",
				"Na década de 1950 regressa a Nova Iorque, abandona a figuração e integra-se na corrente abstracta emergente,  a <i>Escola de Nova Iorque / Expressionismo Abstrato</i>, a par de Mark Rothko, Willem de Kooning e Jackson Pollock. O seu trabalho integra a grande exposição <i>The New American Painting</i>, organizada pelo Museu de Arte Moderna de Nova Iorque em 1958, que dá a conhecer, na Europa, os mais importantes artistas do movimento.",
				"Em 1962 realiza uma grande exposição retrospectiva no Guggenheim Museum de Nova Iorque. A partir de 1968 regressa à figuração, apresentando os primeiros trabalhos dessa nova via numa exposição controversa na Marlborough Gallery de Nova Iorque em 1970.",
				"No fim da década de 1960, Guston começa a exprimir dúvidas sobre a arte abstrata perante a violência do mundo contemporâneo (racismo do Ku Klux Klan, guerra do Vietnam). Ele opera então uma verdadeira viravolta rumo à figura com pinturas e desenhos povoados por seres inquietantes e grotescos, inspiradas pela figura do Klansman (designação do membro do Ku Klux Klan). Este novo stilo é violentamente criticado pelo New York Times (Hilton Kramer) e pelo Time Magazine (Robert Hughes). A maioria dos críticos considera que a volta a uma arte figurativa reminiscente aos cartoons constitui uma traição. Na década de 1970 Guston isola-se em Woodstock, e realiza uma obra intensamente pessoal, antecipando e influenciando a figuração expressionista que haveria de se afirmar internacionalmente já depois da sua morte. Grandes artistas figurativos, como Baselitz, Dana Schutz, Amy Sillman, e muitos outros, nos Estados Unidos ou na Europa, foram marcados pela revolução figurativa iniciada por Philip Guston."
			],
			obras:[
				{
					titl:"Gladiators", ano:1938, imag:"pgu01.jpg",
					texto:"É um dos primeiros exemplos do estilo realista social de Guston, que ele manteria durante todo o seu trabalho como muralista com o WPA (Federal Arts Project / Works Progress Administration). Representa uma tentativa de capturar algo da monumentalidade que ele admirava na arte renascentista italiana, embora seja também uma das primeiras imagens em que ele explora as imagens de figuras encapuzadas, punhos e escudos, que viriam a reaparecer nas suas obras tardias."
				},
				{
					titl:"Zone", ano:1953, imag:"pgu02.jpg",
					texto:"É uma pintura que reflete a extrema focagem do trabalho maduro de Guston, e sugere uma calma cálida, com a sua névoa de marcas vermelhas que preenchem o centro da pintura. Aqui, Guston afia a sua marcação e constrói camadas de tinta a partir de pequenos e rápidos movimentos que são bem diferentes dos gestos mais loucos de alguns dos seus colegas. <i>Olhe para qualquer pintura inspirada</i>, disse ele uma vez, <i>é como um som de gongo; isso o coloca em um estado de reverberação</i>."
				},
				{
					titl:"Last Piece", ano:1958, imag:"pgu03.jpg",
					texto:"Não sendo a última pintura expressionista abstrata de Guston, todavia, representa uma transição das formas cintilantes do início dos anos 1950 para os motivos reconhecíveis de suas obras posteriores, mais figurativas. Se o budismo e os conceitos metafísicos do Nada tivessem influenciado as suas abstrações anteriores, isso representaria um afastamento dessas inspirações."
				},
				{
					titl:"The Studio", ano:1969, imag:"pgu04.jpg",
					texto:"Marca o início do afastamento de Philip Guston da abstração e de volta à figuração que ele praticou durante as décadas de 1930 e 1940, enquanto trabalhava no estilo de pintura mural da WPA (Federal Arts Project / Works Progress Administration). Esta pintura é amplamente reconhecida como um antecipado metaautorretrato, no qual Guston se apresenta, trabalhando no seu cavalete no capuz que ele continuará a empregar como motivo em futuros trabalhos sobre Klansmen (membros do Ku Klux Klan). Exibindo um charuto através do capuz, o pintor mantém a mão livre para criar a sua obra-prima: um autorretrato caricato da sua personalidade encapuzada. Clement Greenberg comentou uma vez que, com exceção de Arshile Gorky, Guston era o artista mais romântico da sua geração."
				},
				{
					titl:"City Limits", ano:1969, imag:"pgu05.jpg",
					texto:"Nesta obra, as personagens encapuzadas de Guston espremem-se num carro, como palhaços, como se fossem causar distúrbios na cidade. Os seus Klansmen (membros do Ku Klux Klan) realizavam, muitas vezes, incontáveis atividades nas suas pinturas, mas acima de tudo, essa imagem reflete um aspecto da motivação original de Guston para voltar ao realismo: um medo crescente da disseminação da desordem política e da agitação na América."
				},
				{
					titl:"Head and Bottle", ano:1975, imag:"pgu06.jpg",
					texto:"Esta obra exemplifica o afastamento de Guston da pintura dos Klansmen (membros do Ku Klux Klan) encapuzados, no final dos anos 60. Ele inventou essa cabeça ciclópica em forma de feijão, sem corpo e com um olho gigante, para representar o artista que tudo vê. Neste trabalho, o olho examina uma garrafa verde, estudando-a como se estivesse prestes a pegar no pincel próximo para transformá-lo em tinta vermelha. No ano seguinte à pintura, Guston foi hospitalizado com esgotamento."
				},
				{
					titl:"Untitled", ano:1980, imag:"pgu07.jpg",
					texto:"Perto do fim da sua vida, Guston não apenas expandiu mais uma vez a sua paleta, para incluir os azuis e amarelos, mas, mais uma vez, também incorporou a abstração em muitas das suas obras."
				}
			]
		},
		{//7-Clyfford Still
			nome:"Clyfford Still", nacion:"americana",
			dataNasc:"19041130", localNasc:"Grandin, North Dakota, EUA",
			dataMorte:"19800623", localMorte:"Baltimore, Maryland, EUA",
			foto:"ClyffordStill.jpg",
			texto:[
				"Clyfford Still estava entre a primeira geração de expressionistas abstratos que desenvolveram uma abordagem nova e poderosa à pintura nos anos imediatamente posteriores à Segunda Guerra Mundial. Os contemporâneos de Still incluem Philip Guston, Franz Kline, Willem de Kooning, Robert Motherwell, Barnett Newman, Jackson Pollock e Mark Rothko. Embora os estilos e abordagens desses artistas variem consideravelmente, o Expressionismo Abstrato é marcado por formas abstratas, pinceladas expressivas e escala monumental, todas usadas para transmitir temas universais sobre criação, vida, luta e morte (a condição humana), temas que assumiram considerável importância durante e após a Segunda Guerra Mundial.",
				"Descrito por muitos como o mais anti-tradicional dos expressionistas abstratos, Still é considerado o fundador das bases para o movimento. A mudança da pintura representacional para a abstração ocorreu entre 1938 e 1942, mais cedo do que os seus colegas, que continuaram a pintar em estilos figurativos-surrealistas até a década de 1940.",
				"Still nasceu em 1904 em Grandin, Dakota do Norte, e passou a infância em Spokane, Washington, e em Bow Island, no sul de Alberta, no Canadá. Embora o expressionismo abstrato seja identificado como um movimento nova-iorquino, os trabalhos formativos de Still foram criados durante vários postos de ensino na costa oeste, primeiro no estado de Washington e depois em San Francisco. Ele também ensinou na Virgínia no início dos anos 1940.",
				"Still visitou Nova Iorque para estadas prolongadas no final da década de 1940 e associou-se às duas galerias que lançaram essa nova arte americana para o mundo: as galerias Art of This Century e Betty Parsons. Ele viveu em Nova Iorque durante a maior parte da década de 1950, durante o auge do movimento expressionista abstrato, também uma época em que ele se tornou cada vez mais crítico do mundo da arte. No início dos anos 1950, Still cortou os laços com as galerias comerciais e em 1961 mudou-se para Maryland, afastando-se ainda mais do sistema artístico estabelecido. Ele permaneceu em Maryland com a sua segunda esposa, Patricia, até à sua morte em 1980.",
				"Em 1979, o Museu Metropolitano de Arte de Nova Iorque organizou a maior pesquisa da arte de Still até hoje e a maior apresentação oferecida pela instituição ao trabalho de um artista vivo. Após a sua morte, todas as obras que não entraram no domínio público foram isoladas da visão pública e académica, fechando o acesso a um dos mais importantes pintores americanos do século XX.",
				"Still é considerado um dos principais pintores do Campo de Cores. As suas pinturas não-figurativas não são objetivas e, sobretudo, prtendem justapor diferentes cores e superfícies numa grande variedade de formações. Ao contrário de Mark Rothko ou Barnett Newman, que organizaram as suas cores de uma maneira relativamente simples (Rothko na forma de retângulos nebulosos, Newman em linhas finas em vastos campos coloridos), os arranjos de Still são menos regulares. Os seus flashes irregulares de cor dão a impressão de que uma camada de cor foi arrancada da pintura, revelando as cores por baixo. Outro ponto de partida com Newman e Rothko é o modo como a tinta é colocada na tela; enquanto Rothko e Newman usavam cores razoavelmente planas e tinta relativamente fina, Still usa um empasto espesso, causando uma subtil variedade de tons que brilham através das superfícies de pintura. As suas grandes obras maduras lembram formas naturais e fenómenos naturais de grande intensidade e mistério; antigas estalagmites, cavernas, folhagens, vistos tanto na escuridão como na luz, dão riqueza poética e profundidade ao seu trabalho. Em 1947, ele começou a trabalhar no formato que ele iria intensificar e refinar durante o resto de sua carreira: um campo de cores aplicado em larga escala com espátula. As quatro cores, preto, amarelo, branco e vermelho., e variações sobre elas (púrpuras e azuis escuros) são predominantes no seu trabalho, embora haja uma tendência nas suas pinturas em usar tons mais escuros."
			],
			obras:[
				{
					titl:"Untitled", ano:1935, imag:"cst01.jpg",
					texto:"Uma amálgama de corpo e paisagem, este trabalho é emblemático da influência do Surrealismo no trabalho de Still em meados da década de 1930. Também mostra o desenvolvimento de uma iconografia pessoal e insinua os interesses de toda a vida do artista na mitologia, no xamanismo nativo americano e nos motivos totémicos. O historiador de arte David Anfam descreveu a imagem como contraditória, a cabeça de expressão séria sugerindo esterilidade, enquanto a sua posição aparente, bem acima de uma paisagem, evoca o espírito crescente."
				},
				{
					titl:"Untitled (Indian Houses, Nespelem)", ano:1936, imag:"cst02.jpg",
					texto:"É um trabalho muito característico do trabalho do artista desde o final da década de 1920 até meados da década de 1930. Foi executado na cidade de Nespelem, na Reserva Indígena Coleville, onde Still co-fundou uma colónia de artistas em 1937. Neste trabalho, Still sintetiza as influências de Gustave Courbet, Paul Cézanne e o Regionalismo Americano, ao mesmo tempo que começa a formular a sua própria filosofia e o seu estilo artístico individual."
				},
				{
					titl:"1944-N No.2 (Red Flash on Black Field)", ano:1944, imag:"cst03.jpg",
					texto:"Este trabalho marca um ponto de viragem essencial na progressão de Still para uma pintura completamente não-representacional. Juntamente com a sua temática puramente abstrata, ele também exibe vários outros dispositivos que ele empregaria ao longo de sua carreira: uma relação dinâmica entre formas verticais e horizontais; uma paleta predominantemente escura destacada por áreas de cor brilhante; uma superfície altamente texturizada resultante do uso de espátula; a adoção de um sistema de nomenclatura não referencial composto de números e datas. Este trabalho também é notável por ser uma das poucas replicações que Still produziu ao longo de sua carreira. Embora os expressionistas abstratos muitas vezes produzissem quadros em série que eram muito semelhantes em composição, a sua concepção do ato pictórico como um evento, como uma expressão de emoção, desencorajou-os a produzir replicações. "
				},
				{
					titl:"1948-C", ano:1948, imag:"cst04.jpg",
					texto:"Este trabalho serve como um exemplo perfeito do estilo maduro de Still, da forma como surgiu em meados da década de 1940. A figuração desapareceu completamente, sendo substituída por nada além de um estranho e crepitante campo de cores. O trabalho apresenta relações caracteristicamente dramáticas entre os elementos de composição, o primeiro plano e o plano de fundo, luz e escuridão, relações que o artista considerou como <i>vida e morte fundindo-se em união temerosa</i>. Também é característico do trabalho de Still do final dos anos 1940 ser dominado pelas cores tiradas de uma paleta no extremo do espectro. Aqui, amarelos quentes."
				},
				{
					titl:"1957-D", ano:1957, imag:"cst05.jpg",
					texto:"Este trabalho reveela a mudança de Still, em meados da década de 1950, para telas mais orientadas verticalmente. Neste caso, os flashes fugazes de cores que interromperam as expansões escuras das pinturas anteriores são agora formas verticais de dimensões monumentais que sobem e descem sobre uma composição quase mural. O historiador de arte David Anfam observou como Still foi atraído para composições que evocam <i>fechamento e libertação, contenção e libertação precária</i>. Aqui a tensão dramática do amarelo e do preto sugere exatamente esse contraste."
				},
				{
					titl:"Untitled", ano:1975, imag:"cst06.jpg",
					texto:"Este trabalho corresponde ao período final da produção de Still após sua mudança em 1961 para a área rural de Maryland. Apresenta uma paleta de cores marcadamente mais clara que suas pinturas anteriores, embora retenha a sensação de uma estrutura solta, semelhante a uma grade, subjacente aos motivos abstratos, uma característica evidente em alguns desses trabalhos anteriores. O trabalho também é notável pelas grandes quantidades de tela nua que ainda permitiam permanecer visíveis na superfície da pintura."
				}
			]
		},
		{//8-Robert Motherwell 
			nome:"Robert Motherwell", nacion:"americana",
			dataNasc:"19150124", localNasc:"Aberdeen, Washington, EUA",
			dataMorte:"19910716", localMorte:"Provincetown, Massachusetts, EUA",
			foto:"RobertMotherwell.jpg",
			texto:[
				"Um talento intelectual articulado entre os expressionistas abstratos, Robert Motherwell nasceu em 1915 no Estado de Washington. Enquanto frequentava a Universidade de Stanford (1932-1937), Motherwell fez a sua primeira viagem à Europa. Depois de receber o seu diploma do curso de filosofia e literatura francesa moderna, ele começou o curso de pós-graduação em filosofia na Universidade de Harvard. Durante uma estada na Europa em 1938-1939, ele teve a sua primeira exposição individual em Paris. Em 1940, ele estudou história da arte com Meyer Schapiro na Universidade de Columbia e, através de Schapiro, conheceu muitos pintores surrealistas europeus. ",
				"É a partir de 1940 que Motherwell passou a dedicar a maior parte do tempo à pintura. Depois de se estabelecer em Nova Iorque em 1941, começou a produzir e a dar palestras sobre arte moderna e associou-se ao grupo de artistas norte-americanos cujo trabalho foi influenciado pelas ideias surrealistas de automatismo, um processo de fazer arte através da livre associação subconsciente: Jackson Pollock. Willem de Kooning, William Baziotes e Hans Hofmann. Motherwell, o mais novo desse grupo de pintores abstratos, procurou criar imagens que transmitissem as verdades emocionais de um <i>eu</i> autêntico e que refletissem uma consciência humana coletiva.",
				"Em 1944, Motherwell realizou sua primeira exposição individual de Nova York na galeria Art of This Century, de Peggy Guggenheim. Nesse mesmo ano, o Museu de Arte Moderna foi o primeiro museu a comprar uma das suas obras. Por volta de 1949, Motherwell alcançou o seu estilo maduro, criando grandes pinturas que empregam formas simples de uma maneira que lembra as fortes imagens pretas sobre branco de Franz Kline. Porém, ao contrário de Kline, as pinturas de Motherwell tinham um forte conteúdo político e literário, especificamente em sua série <i>Elegia para a República Espanhola</i>, pela qual ele ficou mais conhecido. ",
				"Motherwell passou por um período de frustração em meados da década de 1950, quando raramente exibia e destruia muitas obras. Porém, entre 1959 e 1961, foi patente uma assinalável renovação da sua criatividade, com uma renovação e afinação da sua <i>Elegia para a República Espanhola</i>, criando uma nova série de óleos e produzondo inúmeras colagens.",
				"Durante as décadas de 1950 e 1960, Motherwell desenvolveu textos relevantes sobre arte contemporânea e, reconhecido como um dos principais teóricos da arte, ensinou pintura no Black Mountain College, na Carolina do Norte, e no Hunter College, em Nova York. Em 1958 ele casou-se com uma das principais figuras femininas da segunda geração de expressionistas abstratos, a pintora Helen Frankenthaler, que se tornou a sua terceira esposa. Após o divórcio, em 1971, ele estabeleceu residência permanente em Greenwich, Connecticut. Dois anos depois, Motherwell casou-se com a fotógrafa alemã Renate Ponsold. Ele continuou a expandir seu vastíssimo repertório artístico de pinturas, gravuras e colagens. Morreu em 1991 em Provincetown, Massachusetts."
			],
			obras:[
				{
					titl:"Pancho Villa", ano:1943, imag:"rmo01.jpg ",
					texto:"Trata-se de uma referência direta a uma fotografia que Motherwell encontrou do revolucionário mexicano assassinado, Pancho Villa. O trabalho atravessa a linha entre a pintura referencial e o estilo que se tornaria no Expressionismo Abstrato, e inclui várias relações temáticas que aparecem ao longo da obra de Motherwell. Na sua alusão à revolução mexicana, este trabalho também prefigura os temas que conduziriam, mais tarde, à enorme série de Elegias à República Espanhola."
				},
				{
					titl:"The Voyage", ano:1949, imag:"rmo02.jpg ",
					texto:"Esta obra incorpora, simultaneamente, três características insistentes na obra de Motherwell: O geometrismo, as formas icónicas misteriosas e uma paleta de branco e preto com ocres. A obra sugere uma tensão em equilíbrio entre extremos e contrastes."
				},
				{
					titl:"Wall Painting III", ano:1952, imag:"rmo03.jpg ",
					texto:"Trata-se de uma das obras para duas sinagogas, encomendadas a Motherwell para simbolizar a integração dessas congregações judaicas na vida moderna americana após a Segunda Guerra Mundial. Motherwell não era particularmente religioso, mas estava interessado na ideia de um <i>Absoluto</i> e usou essa ideia não apenas para se referir ao espiritual, mas também aos fortes contrastes de cores claras e escuras, absolutos que exprimem os extremos da experiência humana. A forma ocre radiante à esquerda é uma estrela de David estilizada e a forma mais escura à direita pretende exprimir sofrimento. Se lermos essa imagem da direita para a esquerda, como os judeus fazem na Torah, a pintura evoca a passagem dos judeus da escuridão do Holocausto para a alegria de viver livremente e em obediência aos Mandamentos."
				},
				{
					titl:"At Five in the Afternoon", ano:1949, imag:"rmo04.jpg ",
					texto:"Tudo começou com um pequeno desenho a caneta e tinta preta com que Motherwell ilustrou em 1948 um poema de Harold Rosenberg. Um ano depois, Motherwell reinventou o desenho nesta pequena pintura que batizou com o verso <i>A las cinco de la tarde</i>do poema <i>Lament para Ignacio Sanchez Mejias</i>, de Federico Garcia Lorca. Esta obra representa a primeira entrada na série Elegias à República Espanhola e estabelece o sistema formal e estético que definiria toda essa enorme série."
				},
				{
					titl:"Elegy to the Spanish Republic, No. 44", ano:1954, imag:"rmo05.jpg ",
					texto:"Trata-se do trabalho n.º 44 da série de mais de 140 pinturas, as <i>Elegias à República Espanhola</i>, em que Motherwell trabalhou em toda a sua longa carreira. A série funcionou como memorial do artista à Guerra Civil Espanhola, que representou para ele o drama das tragédias humanas de opressão e de injustiça. Este n.º 44 acrescenta algumas notas de cor à sua típica paleta preta e branca, e apresenta também a interação, típica nesta série, de formas retilíneas ovóides e em forma de barra."
				},
				{
					titl:"Elegy to the Spanish Republic, No. 110", ano:1954, imag:"rmo06.jpg ",
					texto:"Trata-se do trabalho n.º 110 da série de mais de 140 pinturas, as <i>Elegias à República Espanhola</i>, em que Motherwell trabalhou em toda a sua longa carreira. A série funcionou como memorial do artista à Guerra Civil Espanhola, que representou para ele o drama das tragédias humanas de opressão e de injustiça. Este n.º 110 é típico da sua paleta preta e branca, e da interação de formas retilíneas ovóides e em forma de barra. O que exatamente essas formas pretendem significar, todavia, tem sido objeto de grande debate. Alguns comparam-nas à arquitetura ou a monumentos antigos, enquanto outros os interpretam como falos e úteros, que, junto com a paleta sombria das imagens, podem sugerir o ciclo da vida e da morte."
				},
				{
					titl:"Elegy to the Spanish Republic, Diversos", ano:"EXPO", imag:"rmo07.jpg ",
					texto:"Perspetiva de uma exposição em Nova Iorque sobre a série <i>Elegias à República Espanhola</i> de Motherwell, mostrando três das obras."
				},
				{
					titl:"The Blue Painting Lesson: A Study in Painterly Logic", ano:1973, imag:"rmo08.jpg ",
					texto:"Grupo de peças azuis, de uma série mais vasta de peças de diferentes cores conhecida como a <i>Série Opens</i>. Cada peça compartilha uma construção formal simples, mas poderosa, com o restante da série: um fundo densamente colorido, quase monocromático, realçado por uma caixa de dois ou três lados que entra na tela do topo da composição. Esta caixa é uma referência abstrata às vistas da janela vistas no trabalho de muitos mestres europeus, e também pode se referir à interseção de mundos internos e externos na vida do artista."
				},
				{
					titl:"Tobacco Roth-Handle", ano:1974, imag:"rmo09.jpg ",
					texto:"Trata-se de uma síntese de técnicas de colagem e gravura, duas tensões importantes no trabalho de Motherwell. A imagem central, identificável na impressão como o invólucro de um maço de cigarros, é uma referência pessoal; é típico do tipo de coisa efémera do quotidiano do artista que começara a procurar o seu caminho nas colagens nos anos 1960. Motherwell considerava as colagens, como um meio criativo através da aplicação de coisas vulgares externas ao artista."
				}
			]
		},
		{//9-Willem De Kooning
			nome:"Willem De Kooning", nacion:"holandesa e americana",
			dataNasc:"19040424", localNasc:"Roterdão, Holanda",
			dataMorte:"19970319", localMorte:"Long Island, Nova Iorque, EUA",
			foto:"WillemDeKooning.jpg",
			texto:[
				"Willem de Kooning nasceu em 24 de abril de 1904, numa família da classe trabalhadora em Roterdão, na Holanda e tornou-se um dos artistas mais influentes da América e do século XX.",
				"Demonstrando desde cedo interesse pela arte, De Kooning foi aprendiz de uma firma líder de design quando tinha doze anos e matriculou-se na escola noturna na prestigiada Academia de Belas Artes e Técnicas de Roterdão que em 1998 foi renomeada em sua homenagem como a Academia Willem de Kooning. Rumou em 1926 para os Estados Unidos com um amigo, estabelecendo-se em Nova Iorque em 1927. Não era a vida de um artista que ele estava procurando nessa altura, pelo contrário, como muitos jovens europeus, era a versão cinematográfica do sonho americano. No entanto, depois de trabalhar brevemente como pintor de casas, estabeleceu-se como artista comercial e mergulhou em sua própria pintura e no mundo artístico de Nova Iorque, fazendo amizade com artistas como Stuart Davis e Arshile Gorky.",
				"Em 1936, durante a Grande Depressão, De Kooning trabalhou na divisão mural da Works Project Administration (WPA), passsando a pintar em tempo integral. No final dos anos 40 e início dos 50, do século passado, De Kooning e os seus contemporâneos de Nova York, incluindo Jackson Pollock, Franz Kline, Robert Motherwell, Adolph Gottlieb, Ad Reinhardt, Barnett Newman e Mark Rothko, tornaram-se notórios por rejeitarem os estilos predominantes, como o Regionalismo, o Surrealismo e o Cubismo, passando a dissolver a relação entre primeiro plano e fundo e usando tinta para criar gestos emotivos e abstratos. Esse movimento foi rotulado como <i>Action Painting</i>, <i>Expressionismo Abstrato</i> ou simplesmente <i>New York School</i>. Até então, Paris era considerada o centro da vanguarda, e a natureza inovadora das contribuições de Picasso era frustrantemente difícil de superar para este grupo de artistas altamente competitivos de Nova Iorque. De Kooning disse claramente: <i>Picasso é o homem a vencer</i>. De Kooning e este grupo finalmente conquistaram os holofotes da Pintura e foram responsáveis pela mudança histórica de atenção para Nova Iorque nos anos seguintes à Segunda Guerra Mundial.",
				"De Kooning tornou-se conhecido como <i>artista entre os artistas</i> entre os seus pares em Nova Iorque e, em 1948, ganhou a aclamação da crítica com sua primeira exposição individual realizada na Charles Egan Gallery. A exposição revelou pinturas a óleo e esmalte densamente trabalhadas, incluindo as suas hoje conhecidas pinturas em preto-e-branco. Esta exposição foi essencial para a reputação de de Kooning. Pouco tempo depois, em 1951, De Kooning fez uma de suas primeiras grandes vendas quando recebeu a Medalha Logan e o Prémio de Compra do Instituto de Arte de Chicago pela sua abstração em grande escala, Escavation (1950). Esta é sem dúvida uma das pinturas mais importantes do século XX. Durante este período, De Kooning ganhou o apoio de Clement Greenberg e, mais tarde, de Harold Rosenberg, os dois críticos principais e rivais de Nova Iorque.",
				"O sucesso de De Kooning não diminuiu a sua necessidade de exploração e experimentação. Em 1953, ele chocou o mundo da arte exibindo uma série de obras figurativas pintadas de forma agressiva, comumente conhecidas como pinturas <i>femininas</i>. Eram mais icónicas do que reais, mas o seu retorno à figuração foi visto por alguns como uma traição aos princípios expressionistas abstratos, que enfatizavam a abstração. Ele perdeu o apoio de Greenberg, mas Rosenberg permaneceu convencido de sua relevância. O Museu de Arte Moderna de Nova Iorque aceitou a mudança de estilo de Kooning como uma evolução e comprou a Woman I (1950 - 1952) em 1953. O que para alguns parecia tão estilisticamente reacionário, para outros era claramente vanguardista. Lutando contra a adesão a qualquer ortodoxia, ele continuou a explorar novos estilos e métodos, muitas vezes desafiando as suas próprias práticas. Costumava dizer, <i>você tem que mudar para permanecer o mesmo</i>.",
				"No final dos anos 50, passou das mulheres para mulheres em paisagens, para o que parecia ser um retorno à abstração <i>pura</i>, com obras respectivamente chamadas de paisagens <i>urbanas</i>, <i>viárias</i> e <i>pastorais</i>; no entanto, ele nunca deixou completamente o mundo dos objetos reais para a pura abstração. Em 1960, ele disse: <i>É realmente absurdo fazer uma imagem, como uma imagem humana, com tinta hoje, quando você pensa sobre isso, já que temos esse problema de fazer ou não fazer isso. Mas, de repente, era ainda mais absurdo não fazê-lo. Então eu temo que eu tenha que seguir os meus desejos</i>. A figura reafirmou-se, agora em sua forma mais carnal.",
				"Grande parte da carreira Kooning é de um constante combate visual entre equilíbrios e desequilíbrios. Na sua última década conseguiu dissipar parte dessa angústia. Saindo de uma metodologia de lixamento, desenho, camadas, raspagem, rotação da tela e repetidamente recuando para considerar cada mudança, as pinturas por vezes serenas dos anos oitenta podem ser vistas como a síntese final de figuração e abstração de De Kooning. Ano após ano, ao longo dos anos 80, de Kooning explorou novas formas de espaço pictórico reveladas por obras com passagens etéreas como fitas; ou alguns com estruturas em que as linhas retas podem flutuar ou parar abruptamente e balancear contra áreas abertas amplas; ou outros de espaços abarrotados, arrojados e líricos. Cores vivas, elementos predominantemente lineares foram justapostos contra áreas brancas subtilmente tonificadas. Com a sua inclinação declarada de abraçar o <i>ordinário</i>, ele estava livre para reconhecer os personagens ou objetos não intelectuais, mundanos ou humorísticos, às vezes perceptíveis nas suas pinturas abstratas. Isso exemplifica novamente a sua insistência na liberdade das ideias doutrinárias sobre o que a arte deveria ser. De Kooning tinha alcançado um lugar mais completamente aberto, menos ansiosamente complexo da sua carreira artística."
			],
			obras:[
				{
					titl:"Seated Woman", ano:1940, imag:"wdk01.jpg",
					texto:"Foi a primeira pintura relevante de De Kooning sobre uma mulher, e evoluiu, curiosamente, de uma anterior encomenda para um retrato. O artista parece ter segurado o retrato encomendado e começou a usá-lo para desenvolver novas imagens. Anteriormente usava imagens contemporâneas de mulheres em revistas ou da sua esposa, Elaine, que até se apresentara como modelo quando o tema do retrato não estava disponível. Esses fatores certamente encorajaram De Kooning a ver as possibilidades de usar um retrato para representar a mulher em geral, em vez de um indivíduo específico. Este quadro foi indubitavelmente influenciado por Arshile Gorky, em particular o figurativo <i>O Artista com a sua Mãe</i>."
				},
				{
					titl:"Pink Angels", ano:1945, imag:"wdk02.jpg",
					texto:"Esta obra marcou um estágio importante na evolução de De Kooning da figuração para a abstração na década de 1940. Os biomorfos rosa carnudos do seu trabalho anterior, formas que evocam olhos e outras formas anatómicas, são violentamente rasgados numa pintura que teria sido inspirada pela carnificina da Segunda Guerra Mundial, e os elementos figurativos são dificilmente distinguíveis do fundo amarelo mostarda. Esse enevoamento completo de figura e do fundo foi um passo importante no desenvolvimento de De Kooning para as pinturas em preto e branco da parte posterior da década."
				},
				{
					titl:"Attic", ano:1949, imag:"wdk03.jpg",
					texto:"Este quadro é um dos mais conhecidos entre uma série de abstrações em preto e branco realizadas a partir de 1947, por De Kooning. <i>De tudo o que passa por mim, só consigo ver um pouco</i>, disse certa vez o artista, <i>mas estou sempre olhando. E vejo muitas vezes</i>. Ele poderia muito bem ter dito isso deste <i>Attic</i>, pois parece combinar fragmentos de figuras e fundos num turbilhão altamente abstrato e dinâmico. Embora se diga que De Kooning tenha sido motivado a iniciar a série por falta de dinheiro (ele encontrou uma oferta barata de esmalte comercial preto), muitos artistas nesse período estavam experimentando o preto e o branco. Em maior ou menor grau, Motherwell, Kline, Baziotes, Gottlieb e Hofmann, todos trabalharam na paleta restrita, e a <i>Guernica</i> de Picasso, que foi exibido em Nova Iorque em 1939, forneceu-lhes um modelo de peso."
				},
				{
					titl:"Excavation", ano:1950, imag:"wdk04.jpg",
					texto:"Marcou o ponto culminante da fase abstrata de De Kooning dos anos 1940. Como no <i>Attic</i>, ele preocupa-se com a relação entre figura e fundo, e as bordas irregulares das formas biomórficas colidem com força dentro do espaço da composição. No entanto, ao contrário do <i>Attic</i>, ele emprega uma gama de cores primárias para destaques. Este exemplo clássico de pintura de ação estava entre os últimos trabalhos concluídos antes de De Kooning retornar à cor e à figura com enorme entusiasmo na sua série <i>Women</i>."
				},
				{
					titl:"Woman I", ano:1952, imag:"wdk05.jpg",
					texto:"É talvez a pintura mais famosa de De Kooning. O processo da sua criação foi descrito por Thomas B. Hess no seu artigo <i>Willem de Kooning pinta um quadro</i>, e o Museu de Arte Moderna de Nova York comprou-o na sua primeira exposição. De Kooning trabalhou na imagem por dois anos, reformulando-a constantemente e de forma agressiva. O seu agente reparou que a tela frequentemente tinham buracos perfurados pela violência das suas pinceladas."
				},
				{
					titl:"July 4th", ano:1957, imag:"wdk06.jpg",
					texto:"No final da década de 1950, De Kooning deixou temporariamente de lado a sua preocupação com as mulheres e começou a explorar a paisagem, embora muitas vezes pareça haver poucas referências diretas à paisagem nessas pinturas. Essas obras do final dos anos 1950 e início dos anos 1960 foram feitas durante o período em que De Kooning e Franz Kline compartilhavam uma relação de influência mútua, e a estrutura subjacente ao <i>July 4th</i> é certamente reminiscente de Kline. Curiosamente, Kline, que há muito pintava em preto e branco, começou a usar cores nesse período."
				},
				{
					titl:"Women Singing II", ano:1967, imag:"wdk07.jpg",
					texto:"Este trabalho é típico do estilo de De Kooning ao retornar à figura, ao começar a fazer uma nova série de pinturas de mulheres, pouco depois de se mudar permanentemente para Long Island. Tal como a sua série anterior de mulheres, elas são altamente abstratas, mas são menos ferozes e mais obviamente erotizadas, com lábios vermelhos brilhantes e longos cabelos loiros e mais próximas da caricatura. Foram inspiradas pelas novas modas e ídolos pop da década de 1960."
				},
				{
					titl:"Untitled VII", ano:1985, imag:"wdk08.jpg",
					texto:"Nesta pintura tardia de 1985, De Kooning simplificou enormemente as suas pinceladas e cores. Ao contrário dos seus trabalhos anteriores, que foram caracterizados por superfícies muito ocupadas, neste caso aparentemente emprega um número escasso de pinceladas que são destacadas pela abundância de branco ao redor delas. Ele também se afastou do pesado empastelamento e retornou às superfícies lisas e lixadas de algumas de suas imagens figurativas dos anos 1940. Essas obras foram recebidas como confirmação dos poderes continuados do pintor, no entanto, à medida que a década avançava, ficou claro que as capacidades mentais de Kooning estavam diminuindo, e em 1989 ele foi diagnosticado com a doença de Alzheimer. A década de 1990 assistiu a um debate vigoroso sobre a qualidade do trabalho tardio do pintor, os críticos questionando se ele brotava do seu intelecto ou da sua intuição."
				}
			]
		}
	]
};